name: weatherpro_flutter
description: A professional weather app built with Flutter that displays current weather conditions.
# Prevent accidental publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.4.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
